version: "3.7"

services:

  # php-fpm 8.1
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ${PROJECT_PATH}/:/var/www/html/app
    networks:
      - backend

  # nginx
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PROJECT_PATH}/:/var/www/html/app
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx
    environment:
      - TZ=Asia/Taipei
    networks:
      - backend

  # Mysql
  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/mysql-logs:/var/log
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - backend

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    networks:
        - backend

# Redis
  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    container_name: redis
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge